CREATE TABLE crm (
        crm_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        crm VARCHAR(45) NOT NULL,
        uf VARCHAR(2) NOT NULL,
        specialty VARCHAR(255),
        user_id BIGINT,
        PRIMARY KEY (crm_id)
);

CREATE TABLE user_system (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        surname VARCHAR(255),
        password VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        mobile_phone VARCHAR(255),
        authorization_status VARCHAR(40),
        profile_type VARCHAR(20),
        token_id BIGINT,
        PRIMARY KEY (user_id)
);

CREATE TABLE user_token (
        token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        access_token VARCHAR(1000),
        refresh_token VARCHAR(1000),
        authorization_status VARCHAR(40),
        expiration TIMESTAMP,
        PRIMARY KEY (token_id)
);

ALTER TABLE crm
       ADD CONSTRAINT fk_user_id
       FOREIGN KEY (user_id)
       REFERENCES user_system;

ALTER TABLE user_system
      ADD CONSTRAINT fk_token_id
      FOREIGN KEY (token_id)
      REFERENCES user_token;

ALTER TABLE user_system
      ADD CONSTRAINT email_unique
      UNIQUE (email);